### PR TITLE
Apply `black` and `isort`

### PR DESCRIPTION
**Pull request by cthoyt**
I was recently trying to read the codebase and found that the formatting was very distracting. This pull request uses `black` to apply a consistent style to the code and `isort` to apply a consistent style. It also adds respective flake8 plugins to the CI workflow

### CODE REVIEW

**Comment by zqfang** [comment]
Sorry, I still havn't fixed the merge issue...

**Comment by cthoyt** [comment]
@zqfang its exceedingly difficult to reconcile the upstream with a branch with so many style changes. If you like the idea of this PR, I will take care of it for you

**Comment by zqfang** [comment]
@cthoyt  Thank you very much for your work! Yeah, we definitely need a more readable codebase. But I have not  experience with flake8. If you think it worth your time to help improve the codebase, please do help. I will merge it to the main branch once it works.

**Comment by cthoyt** [comment]
@zqfang I reran black and it should be good now, you should approve that my fork can run the CI in the PR dialogue in this page

**Comment by zqfang** [comment]
@cthoyt , Many thanks for your contribution. Let's make better software.

**Pull request merged**
